apiVersion: v1
kind: Service
metadata:
  name: productcrud-api
  namespace: db
spec:
  selector:
    app: productcrud-api
  ports:
    - name: http
      port: 8000
      targetPort: 8000
  type: NodePort

